services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - 80:80
      - 443:443
    volumes:
      - "www:/var/www/html"

# networks:

volumes:
  www:
    driver: local
    driver_opts:
      device: /home/artmende/data/www
      type: volume
      o: bind

  db:
    driver: local
    driver_opts:
      device: /home/artmende/data/db
      type: volume
      o: bind
