services:
  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    env_file: ./.env
    restart: always
    volumes:
      - "db:/var/lib/mysql"
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    restart: always
    volumes:
      - "www:/var/www/html"
      # - "www:/www_folder"
    networks:
      - inception

  nginx:
    depends_on:
      - mariadb
      - wordpress
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - 443:443
    volumes:
      - "www:/var/www/html"
    networks:
      - inception

networks:
  inception:

volumes:
  www:
    driver: local
    driver_opts:
      device: /home/artmende/data/www
      type: volume
      o: bind

  db:
    driver: local
    driver_opts:
      device: /home/artmende/data/db
      type: volume
      o: bind
